version: 2
jobs:
    build-debian:
        docker:
            - image: continuumio/miniconda3
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    conda env create -f environment.yml
            - run:
                name: Build/install/test phycon
                command: |
                    source activate phycon-env
                    python setup.py install
                    cd phycon
                    pytest -v --cov=phycon
                    flake8 --exit-zero phycon
                    pylint phycon
workflows:
    version: 2
    build-all:
        jobs:
            - build-debian
